/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 02:18:31 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetSocketAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetSocketAddress;
import org.jboss.netty.channel.Channel;
import org.jboss.netty.channel.DefaultChannelPipeline;
import org.jboss.netty.channel.local.DefaultLocalClientChannelFactory;
import org.jboss.netty.channel.local.LocalChannel;
import org.junit.runner.RunWith;
import org.traccar.protocol.AquilaProtocol;
import org.traccar.protocol.AquilaProtocolDecoder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class AquilaProtocolDecoder_ESTest extends AquilaProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AquilaProtocol aquilaProtocol0 = new AquilaProtocol();
      AquilaProtocolDecoder aquilaProtocolDecoder0 = new AquilaProtocolDecoder(aquilaProtocol0);
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("io1", 12);
      try { 
        aquilaProtocolDecoder0.decode((Channel) null, inetSocketAddress0, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AquilaProtocol aquilaProtocol0 = new AquilaProtocol();
      AquilaProtocolDecoder aquilaProtocolDecoder0 = new AquilaProtocolDecoder(aquilaProtocol0);
      DefaultLocalClientChannelFactory defaultLocalClientChannelFactory0 = new DefaultLocalClientChannelFactory();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      LocalChannel localChannel0 = defaultLocalClientChannelFactory0.newChannel(defaultChannelPipeline0);
      MockInetSocketAddress mockInetSocketAddress0 = new MockInetSocketAddress("charge", 0);
      try { 
        aquilaProtocolDecoder0.decode(localChannel0, mockInetSocketAddress0, defaultChannelPipeline0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jboss.netty.channel.DefaultChannelPipeline cannot be cast to java.lang.String
         //
         verifyException("org.traccar.protocol.AquilaProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AquilaProtocol aquilaProtocol0 = new AquilaProtocol();
      AquilaProtocolDecoder aquilaProtocolDecoder0 = new AquilaProtocolDecoder(aquilaProtocol0);
      DefaultLocalClientChannelFactory defaultLocalClientChannelFactory0 = new DefaultLocalClientChannelFactory();
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      LocalChannel localChannel0 = defaultLocalClientChannelFactory0.newChannel(defaultChannelPipeline0);
      InetSocketAddress inetSocketAddress0 = MockInetSocketAddress.createUnresolved("fuel", 147);
      aquilaProtocolDecoder0.decode(localChannel0, inetSocketAddress0, "fuel");
      assertEquals(0, (int)localChannel0.getId());
  }
}
