/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 13:07:47 GMT 2024
 */

package hu.oe.nik.szfmv.automatedcar;

import org.junit.Test;
import static org.junit.Assert.*;
import hu.oe.nik.szfmv.automatedcar.AutomatedCar;
import hu.oe.nik.szfmv.automatedcar.bus.packets.car.CarPacket;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class AutomatedCar_ESTest extends AutomatedCar_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AutomatedCar automatedCar0 = new AutomatedCar(2265, 360, "");
      automatedCar0.setRotation(360);
      automatedCar0.drive();
      assertEquals(1.8584374907635866, automatedCar0.getRotation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AutomatedCar automatedCar0 = new AutomatedCar(2265, 360, "");
      automatedCar0.getInputValues();
      assertEquals(108, automatedCar0.getWidth());
      assertEquals(240, automatedCar0.getHeight());
      assertEquals(200, automatedCar0.getY());
      assertEquals(200, automatedCar0.getX());
      assertEquals(4.71238898038469, automatedCar0.getRotation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AutomatedCar automatedCar0 = new AutomatedCar(2265, 360, "");
      CarPacket carPacket0 = automatedCar0.getCarValues();
      assertEquals(200, carPacket0.getY());
      assertEquals(200, carPacket0.getX());
      assertEquals(240, automatedCar0.getHeight());
      assertEquals(108, automatedCar0.getWidth());
      assertEquals(4.71238898038469, carPacket0.getRotation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AutomatedCar automatedCar0 = new AutomatedCar(2265, 360, "");
      automatedCar0.getPowertrainValues();
      assertEquals(108, automatedCar0.getWidth());
      assertEquals(240, automatedCar0.getHeight());
      assertEquals(4.71238898038469, automatedCar0.getRotation(), 0.01);
      assertEquals(200, automatedCar0.getY());
      assertEquals(200, automatedCar0.getX());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AutomatedCar automatedCar0 = new AutomatedCar(2265, 360, "");
      automatedCar0.drive();
      automatedCar0.getPowertrainValues();
      assertEquals(200, automatedCar0.getX());
      assertEquals(200, automatedCar0.getY());
      assertEquals(240, automatedCar0.getHeight());
      assertEquals(4.71238898038469, automatedCar0.getRotation(), 0.01);
      assertEquals(108, automatedCar0.getWidth());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AutomatedCar automatedCar0 = new AutomatedCar(2265, 360, "");
      automatedCar0.getUltrasonicSensors();
      assertEquals(240, automatedCar0.getHeight());
      assertEquals(108, automatedCar0.getWidth());
      assertEquals(200, automatedCar0.getX());
      assertEquals(200, automatedCar0.getY());
      assertEquals(4.71238898038469, automatedCar0.getRotation(), 0.01);
  }
}
