/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 06:48:18 GMT 2024
 */

package org.openpnp.machine.reference.feeder;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.openpnp.machine.reference.feeder.ReferenceStripFeeder;
import org.openpnp.model.Board;
import org.openpnp.model.BoardLocation;
import org.openpnp.model.Location;
import org.openpnp.model.Placement;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ReferenceStripFeeder_ESTest extends ReferenceStripFeeder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Board board0 = new Board();
      BoardLocation boardLocation0 = new BoardLocation(board0);
      Location location0 = boardLocation0.getLocation();
      // Undeclared exception!
      try { 
        ReferenceStripFeeder.getAngleFromPoint(location0, (Location) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.openpnp.machine.reference.feeder.ReferenceStripFeeder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Placement placement0 = new Placement("ba;o");
      Location location0 = placement0.getLocation();
      double double0 = ReferenceStripFeeder.getAngleFromPoint(location0, location0);
      assertEquals(360.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReferenceStripFeeder referenceStripFeeder0 = null;
      try {
        referenceStripFeeder0 = new ReferenceStripFeeder();
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // Configuration instance not yet initialized.
         //
         verifyException("org.openpnp.model.Configuration", e);
      }
  }
}
