/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 04:09:23 GMT 2024
 */

package com.fasterxml.jackson.databind.jsontype.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.databind.jsontype.NamedType;
import com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver;
import java.lang.reflect.Array;
import java.net.Proxy;
import java.util.LinkedHashSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class StdSubtypeResolver_ESTest extends StdSubtypeResolver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StdSubtypeResolver stdSubtypeResolver0 = new StdSubtypeResolver();
      Class<Proxy.Type>[] classArray0 = (Class<Proxy.Type>[]) Array.newInstance(Class.class, 2);
      Class<Proxy.Type> class0 = Proxy.Type.class;
      classArray0[0] = class0;
      // Undeclared exception!
      try { 
        stdSubtypeResolver0.registerSubtypes(classArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StdSubtypeResolver stdSubtypeResolver0 = new StdSubtypeResolver();
      // Undeclared exception!
      try { 
        stdSubtypeResolver0.registerSubtypes((NamedType[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StdSubtypeResolver stdSubtypeResolver0 = new StdSubtypeResolver();
      NamedType[] namedTypeArray0 = new NamedType[6];
      stdSubtypeResolver0.registerSubtypes(namedTypeArray0);
      assertEquals(6, namedTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StdSubtypeResolver stdSubtypeResolver0 = new StdSubtypeResolver();
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 0);
      stdSubtypeResolver0.registerSubtypes(classArray0);
      assertEquals(0, classArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StdSubtypeResolver stdSubtypeResolver0 = new StdSubtypeResolver();
      NamedType[] namedTypeArray0 = new NamedType[2];
      LinkedHashSet<NamedType> linkedHashSet0 = new LinkedHashSet<NamedType>();
      stdSubtypeResolver0._registeredSubtypes = linkedHashSet0;
      stdSubtypeResolver0.registerSubtypes(namedTypeArray0);
      assertEquals(2, namedTypeArray0.length);
  }
}
