/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun May 26 13:12:41 GMT 2024
 */

package io.github.classgraph;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ClassGraph_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "io.github.classgraph.ClassGraph"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.OFF; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ClassGraph_ESTest_scaffolding.class.getClassLoader() ,
      "io.github.classgraph.ClassGraph",
      "io.github.classgraph.classloaderhandler.JBossClassLoaderHandler",
      "io.github.classgraph.utils.CallStackReader$3",
      "io.github.classgraph.utils.ClasspathOrModulePathEntry",
      "io.github.classgraph.utils.WhiteBlackList",
      "io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry",
      "io.github.classgraph.utils.NestedJarHandler$3$1",
      "io.github.classgraph.classloaderhandler.URLClassLoaderHandler",
      "io.github.classgraph.utils.SingletonMap$SingletonHolder",
      "io.github.classgraph.utils.NestedJarHandler$1$1",
      "io.github.classgraph.utils.WhiteBlackList$WhiteBlackListWholeString",
      "io.github.classgraph.classloaderhandler.SpringBootRestartClassLoaderHandler",
      "io.github.classgraph.utils.SimpleThreadFactory",
      "io.github.classgraph.utils.WorkQueue$1",
      "io.github.classgraph.ModuleRef",
      "io.github.classgraph.Scanner$ClasspathOrModulePathEntryToClasspathElementMap",
      "io.github.classgraph.classloaderhandler.EquinoxContextFinderClassLoaderHandler",
      "io.github.classgraph.Scanner$1",
      "io.github.classgraph.utils.WhiteBlackList$WhiteBlackListPrefix",
      "io.github.classgraph.utils.SingletonMap",
      "io.github.classgraph.classloaderhandler.WebsphereLibertyClassLoaderHandler",
      "io.github.classgraph.utils.NestedJarHandler$4",
      "io.github.classgraph.utils.NestedJarHandler$5",
      "io.github.classgraph.utils.CallStackReader$CallerResolver",
      "io.github.classgraph.utils.VersionFinder$OperatingSystem",
      "io.github.classgraph.utils.NestedJarHandler$2",
      "io.github.classgraph.utils.NestedJarHandler$3",
      "io.github.classgraph.utils.NestedJarHandler$1",
      "io.github.classgraph.classloaderhandler.FelixClassLoaderHandler",
      "io.github.classgraph.utils.CallStackReader",
      "io.github.classgraph.utils.NestedJarHandler",
      "io.github.classgraph.utils.ReflectionUtils",
      "io.github.classgraph.classloaderhandler.WeblogicClassLoaderHandler",
      "io.github.classgraph.Scanner",
      "io.github.classgraph.ClassGraph$ScanResultProcessor",
      "io.github.classgraph.utils.InterruptionChecker",
      "io.github.classgraph.ModuleReaderProxy",
      "io.github.classgraph.classloaderhandler.WebsphereTraditionalClassLoaderHandler",
      "io.github.classgraph.utils.FastPathResolver",
      "io.github.classgraph.classloaderhandler.OSGiDefaultClassLoaderHandler",
      "io.github.classgraph.utils.ClassLoaderAndModuleFinder",
      "io.github.classgraph.ClassGraph$ClasspathElementFilter",
      "io.github.classgraph.utils.WorkQueue$WorkUnitProcessor",
      "io.github.classgraph.utils.LogNode",
      "io.github.classgraph.utils.JarUtils",
      "io.github.classgraph.utils.FileUtils",
      "io.github.classgraph.ScanResult",
      "io.github.classgraph.utils.JarfileMetadataReader",
      "io.github.classgraph.ScanSpec",
      "io.github.classgraph.utils.ClasspathFinder$1",
      "io.github.classgraph.classloaderhandler.FallbackClassLoaderHandler",
      "io.github.classgraph.utils.FileUtils$2",
      "io.github.classgraph.utils.FileUtils$1",
      "io.github.classgraph.classloaderhandler.EquinoxClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.ClassLoaderHandler",
      "io.github.classgraph.ClassGraph$FailureHandler",
      "io.github.classgraph.utils.ClasspathFinder",
      "io.github.classgraph.classloaderhandler.ClassLoaderHandler$DelegationOrder",
      "io.github.classgraph.classloaderhandler.AntClassLoaderHandler",
      "io.github.classgraph.utils.VersionFinder",
      "io.github.classgraph.utils.WorkQueue",
      "io.github.classgraph.classloaderhandler.JPMSClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry",
      "io.github.classgraph.utils.ClasspathOrder",
      "io.github.classgraph.utils.Recycler",
      "io.github.classgraph.utils.WhiteBlackList$WhiteBlackListLeafname"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("io.github.classgraph.ClassGraph$FailureHandler", false, ClassGraph_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("io.github.classgraph.ClassGraph$ScanResultProcessor", false, ClassGraph_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ClassGraph_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "io.github.classgraph.ClassGraph",
      "io.github.classgraph.utils.VersionFinder$OperatingSystem",
      "io.github.classgraph.utils.VersionFinder",
      "io.github.classgraph.utils.FastPathResolver",
      "io.github.classgraph.utils.FileUtils$2",
      "io.github.classgraph.utils.FileUtils",
      "io.github.classgraph.utils.JarUtils",
      "io.github.classgraph.ScanSpec",
      "io.github.classgraph.utils.WhiteBlackList",
      "io.github.classgraph.utils.WhiteBlackList$WhiteBlackListWholeString",
      "io.github.classgraph.utils.WhiteBlackList$WhiteBlackListPrefix",
      "io.github.classgraph.utils.WhiteBlackList$WhiteBlackListLeafname",
      "io.github.classgraph.utils.AutoCloseableExecutorService",
      "io.github.classgraph.utils.SimpleThreadFactory",
      "io.github.classgraph.Scanner",
      "io.github.classgraph.utils.InterruptionChecker",
      "io.github.classgraph.utils.LogNode",
      "io.github.classgraph.utils.NestedJarHandler",
      "io.github.classgraph.utils.SingletonMap",
      "io.github.classgraph.utils.NestedJarHandler$1",
      "io.github.classgraph.utils.NestedJarHandler$2",
      "io.github.classgraph.utils.NestedJarHandler$3",
      "io.github.classgraph.utils.NestedJarHandler$4",
      "io.github.classgraph.utils.NestedJarHandler$5",
      "io.github.classgraph.ModuleRef",
      "io.github.classgraph.utils.ReflectionUtils",
      "io.github.classgraph.Scanner$ClasspathOrModulePathEntryToClasspathElementMap",
      "io.github.classgraph.utils.ClasspathFinder",
      "io.github.classgraph.utils.ClassLoaderAndModuleFinder",
      "io.github.classgraph.utils.CallStackReader",
      "io.github.classgraph.utils.CallStackReader$3",
      "io.github.classgraph.utils.CallStackReader$CallerResolver",
      "io.github.classgraph.utils.ClasspathOrder",
      "io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry",
      "io.github.classgraph.classloaderhandler.AntClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.EquinoxClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.EquinoxContextFinderClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.FelixClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.JBossClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.WeblogicClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.WebsphereLibertyClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.WebsphereTraditionalClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.OSGiDefaultClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.SpringBootRestartClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.URLClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.JPMSClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.FallbackClassLoaderHandler",
      "io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry",
      "io.github.classgraph.classloaderhandler.ClassLoaderHandler$DelegationOrder",
      "io.github.classgraph.utils.ClasspathFinder$1",
      "io.github.classgraph.utils.ClasspathOrModulePathEntry",
      "io.github.classgraph.Scanner$1",
      "io.github.classgraph.utils.WorkQueue",
      "io.github.classgraph.utils.WorkQueue$1",
      "io.github.classgraph.utils.SingletonMap$SingletonHolder"
    );
  }
}
