/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 03:35:05 GMT 2024
 */

package correct_java_programs;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import correct_java_programs.LONGEST_COMMON_SUBSEQUENCE;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class LONGEST_COMMON_SUBSEQUENCE_ESTest extends LONGEST_COMMON_SUBSEQUENCE_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LONGEST_COMMON_SUBSEQUENCE lONGEST_COMMON_SUBSEQUENCE0 = new LONGEST_COMMON_SUBSEQUENCE();
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("XGPnaKro;pvU_02", "XGPnaKro;pvU_02");
      String string0 = "gA>LsW7CiQ39T$_y";
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("gA>LsW7CiQ39T$_y", "gA>LsW7CiQ39T$_y");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("correct_java_programs.LONGEST_COMMON_SUBSEQUENCE", "correct_java_programs.LONGEST_COMMON_SUBSEQUENCE");
      String string1 = "";
      String string2 = "";
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      // Undeclared exception!
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("correct_java_programs.LONGEST_COMMON_SUBSEQUENCE", "`n}kJZ,?W=");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = "[%";
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("[%", "[%");
      String string1 = "SUT(T\\CV";
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("[%", "SUT(TCV");
      String string2 = "I36w:L\"YZt2/(~C,8xB";
      // Undeclared exception!
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence(";%[O6Ctma", "I36w:L\"YZt2/(~C,8xB");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      LONGEST_COMMON_SUBSEQUENCE lONGEST_COMMON_SUBSEQUENCE0 = new LONGEST_COMMON_SUBSEQUENCE();
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("iS.<", "iS.<");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("Z{d,Z[2nDFa_", "Z{d,Z[2nDFa_");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "cOXJ|I<J@ADQUJ+}");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", (String) null);
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "Z{d,Z[2nDFa_");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", (String) null);
      // Undeclared exception!
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("gyu!IFBkZP]n9R$", "a'I>Cs]!h~ 8oZZq");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "ld\"U'6l,2");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("ld\"U'6l,2", "");
      LONGEST_COMMON_SUBSEQUENCE lONGEST_COMMON_SUBSEQUENCE0 = new LONGEST_COMMON_SUBSEQUENCE();
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("6Y1y~M4OcQZPU", "{s=_");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("|", "<.");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      String string0 = LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "<.");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence((String) null, "nC;");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = "correct_java_programs.LONGEST_COMMON_SUBSEQUENCE";
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("correct_java_programs.LONGEST_COMMON_SUBSEQUENCE", "correct_java_programs.LONGEST_COMMON_SUBSEQUENCE");
      LONGEST_COMMON_SUBSEQUENCE lONGEST_COMMON_SUBSEQUENCE0 = new LONGEST_COMMON_SUBSEQUENCE();
      // Undeclared exception!
      try { 
        LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("9%24``MV2;}>\"UJ", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      LONGEST_COMMON_SUBSEQUENCE lONGEST_COMMON_SUBSEQUENCE0 = new LONGEST_COMMON_SUBSEQUENCE();
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "q'TM^?gcx(");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      String string0 = LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LONGEST_COMMON_SUBSEQUENCE lONGEST_COMMON_SUBSEQUENCE0 = new LONGEST_COMMON_SUBSEQUENCE();
      String string0 = LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("=&e~F_nZ5p", "=&e~F_nZ5p");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("RU1fhmY{", "");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", (String) null);
      String string1 = LONGEST_COMMON_SUBSEQUENCE.longest_common_subsequence("", "");
      assertFalse(string1.equals((Object)string0));
  }
}
