/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 03:24:27 GMT 2024
 */

package java_programs;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java_programs.FLATTEN;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class FLATTEN_ESTest extends FLATTEN_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayList<Object> arrayList0 = new ArrayList<Object>();
      ArrayList arrayList1 = (ArrayList)FLATTEN.flatten(arrayList0);
      assertTrue(arrayList1.isEmpty());
  }
}
