/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 05 06:45:02 GMT 2024
 */

package org.openpnp.machine.reference.feeder;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ReferenceStripFeeder_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.openpnp.machine.reference.feeder.ReferenceStripFeeder"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.OFF; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ReferenceStripFeeder_ESTest_scaffolding.class.getClassLoader() ,
      "org.openpnp.model.AbstractModelObject",
      "org.simpleframework.xml.stream.Style",
      "org.openpnp.spi.Movable",
      "org.simpleframework.xml.Serializer",
      "org.openpnp.spi.Feeder",
      "org.openpnp.spi.base.AbstractFeeder",
      "org.simpleframework.xml.strategy.Strategy",
      "org.openpnp.spi.PropertySheetHolder",
      "org.openpnp.machine.reference.ReferenceFeeder",
      "org.openpnp.util.ResourceUtils$PathResolutionException",
      "org.openpnp.gui.support.Wizard",
      "org.openpnp.ConfigurationListener",
      "org.openpnp.model.Configuration",
      "org.openpnp.model.Identifiable",
      "org.openpnp.spi.HeadMountable",
      "org.openpnp.machine.reference.feeder.ReferenceStripFeeder$TapeType",
      "org.openpnp.model.Named",
      "org.openpnp.machine.reference.feeder.ReferenceStripFeeder",
      "org.openpnp.spi.WizardConfigurable",
      "org.openpnp.spi.Locatable"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ReferenceStripFeeder_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.openpnp.model.AbstractModelObject",
      "org.openpnp.spi.base.AbstractFeeder",
      "org.openpnp.machine.reference.ReferenceFeeder",
      "org.openpnp.machine.reference.feeder.ReferenceStripFeeder",
      "org.openpnp.machine.reference.feeder.ReferenceStripFeeder$TapeType",
      "org.openpnp.model.LengthUnit",
      "org.openpnp.gui.MainFrame",
      "org.openpnp.model.Configuration",
      "org.openpnp.machine.reference.feeder.ReferenceDragFeeder$Vision",
      "org.openpnp.model.Rectangle",
      "org.openpnp.model.Location",
      "org.openpnp.spi.base.AbstractCamera",
      "nu.pattern.OpenCV",
      "nu.pattern.OpenCV$SharedLoader",
      "org.opencv.core.Core",
      "nu.pattern.OpenCV$OS",
      "nu.pattern.OpenCV$Arch",
      "nu.pattern.OpenCV$1",
      "nu.pattern.OpenCV$TemporaryDirectory",
      "nu.pattern.OpenCV$TemporaryDirectory$1",
      "nu.pattern.OpenCV$SharedLoader$Holder",
      "org.openpnp.machine.reference.ReferenceCamera",
      "org.openpnp.machine.reference.camera.OpenCvCamera",
      "org.openpnp.machine.reference.feeder.ReferenceDragFeeder",
      "org.openpnp.machine.reference.driver.AbstractSerialPortDriver",
      "org.openpnp.machine.reference.driver.GcodeDriver",
      "org.openpnp.spi.base.AbstractNozzle",
      "org.openpnp.machine.reference.ReferenceNozzle",
      "org.openpnp.util.IdentifiableList",
      "org.openpnp.model.Length",
      "org.openpnp.spi.Camera$Looking",
      "org.openpnp.machine.reference.driver.SimulatorDriver"
    );
  }
}
